# -*- coding: utf-8 -*-
"""Trabajo final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wf_HJ_LWKcSzQiqesQlP60rUAtibol6F
"""

import pandas as pd

# ==========================================================
# 1. CREACIÓN DE DATAFRAMES
# ==========================================================

# Tabla de Estudiantes
datos_estudiantes = {
    "ID": [1, 2, 3, 4, 5, 6],
    "Nombre": ["Ana", "Carlos", "Maria", "Jose", "Laura", "Pedro"],
    "Edad": [20, 22, 19, 25, 21, 23],
    "Curso": ["Python", "Python", "SQL", "SQL", "Python", "SQL"],
    "Nota": [95, 78, 88, 65, 92, 55],
    "Asistencia": [90, 85, 95, 70, 98, 60]
}
df_estudiantes = pd.DataFrame(datos_estudiantes)

# Tabla de Animales
datos_animales = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    "Animal": [

        "León", "Tigre", "Elefante", "Jirafa", "Cebra",
        "Mono", "Gorila", "Oso", "Panda", "Canguro",
        "Hipopótamo", "Rinoceronte", "Cocodrilo", "Serpiente",
        "Águila", "Pingüino", "Flamenco", "Tortuga", "Lobo", "Zorro"
    ],
    "Especie": [
        "Panthera leo", "Panthera tigris", "Loxodonta africana",
        "Giraffa camelopardalis", "Equus quagga", "Macaca",
        "Gorilla gorilla", "Ursus arctos", "Ailuropoda melanoleuca",
        "Macropus", "Hippopotamus amphibius", "Ceratotherium simum",
        "Crocodylus", "Python", "Aquila", "Spheniscidae",
        "Phoenicopterus", "Testudines", "Canis lupus", "Vulpes vulpes"
    ],
    "Edad": [8, 6, 15, 10, 7, 5, 12, 9, 4, 6, 14, 18, 11, 7, 13, 5, 8, 20, 6, 4],
    "Genero": [
        "Macho", "Hembra", "Hembra", "Macho", "Hembra",
        "Macho", "Hembra", "Macho", "Hembra", "Macho",
        "Hembra", "Macho", "Macho", "Hembra", "Macho",
        "Hembra", "Hembra", "Macho", "Macho", "Hembra"
    ],
    "Habitat": [
        "Sabana", "Selva", "Sabana", "Sabana", "Sabana",
        "Selva", "Selva", "Bosque", "Bosque", "Pradera",
        "Río", "Sabana", "Río", "Selva", "Montaña",
        "Antártida", "Humedal", "Río", "Bosque", "Bosque"
    ],
    "Alimentacion": [
        "Carnívoro", "Carnívoro", "Herbívoro", "Herbívoro", "Herbívoro",
        "Omnívoro", "Herbívoro", "Omnívoro", "Herbívoro", "Herbívoro",
        "Herbívoro", "Herbívoro", "Carnívoro", "Carnívoro", "Carnívoro",
        "Carnívoro", "Herbívoro", "Herbívoro", "Carnívoro", "Omnívoro"
    ]
}
df_animales = pd.DataFrame(datos_animales)


# ==========================================================
# 2. MENÚ PRINCIPAL
# ==========================================================

while True:
    print("\n================================")
    print("        MENÚ PRINCIPAL")
    print("================================")
    print("1. Saludar")
    print("2. Mostrar Nombre")
    print("3. Sumar Números")
    print("4. Mostrar Promedio")
    print("5. Mostrar Tabla de Estudiantes")
    print("6. Mostrar Info de Estudiantes")
    print("7. Mostrar Estadísticas de Estudiantes")
    print("8. Buscar Estudiante")
    print("9. Mostrar Estudiantes Aprobados")
    print("10. Mostrar Estudiantes Reprobados")
    print("11. Promedio General de Notas")
    print("12. Promedio de Notas por Curso")
    print("13. Buscar Animal")
    print("14. Mostrar Tabla de Animales")
    print("15. Nombre profesor")
    print("16. Salir")
    print("================================")

    opcion = input("Seleccione una opción: ")

    # ------------------------------------------------------
    # OPCIONES PRINCIPALES 
    # ------------------------------------------------------
    if opcion == "1":
        print("\n¡Hola! Bienvenido al programa.")

    elif opcion == "2":
        nombre = input("\nDigite su nombre: ")
        print("Su nombre es:", nombre)

    elif opcion == "3":
        numero1 = float(input("\nDigite el primer número: "))
        numero2 = float(input("Digite el segundo número: "))
        suma = numero1 + numero2
        print("La suma es:", suma)

    elif opcion == "4":
        n1 = float(input("\nDigite la primera nota: "))
        n2 = float(input("Digite la segunda nota: "))
        n3 = float(input("Digite la tercera nota: "))
        promedio = (n1 + n2 + n3) / 3
        print("El promedio es:", round(promedio, 2))

    # ------------------------------------------------------
    # OPCIONES RELACIONADAS A LOS ESTUDIANTES
    # ------------------------------------------------------
    elif opcion == "5":
        print("\n===== TABLA DE ESTUDIANTES =====")
        print(df_estudiantes)

    elif opcion == "6":
        print("\n===== INFORMACIÓN =====")
        df_estudiantes.info()

    elif opcion == "7":
        print("\n===== ESTADÍSTICAS =====")
        print(df_estudiantes.describe())

    elif opcion == "8":
        nombre_buscar = input("\nDigite el nombre del estudiante: ")
        resultado = df_estudiantes[df_estudiantes["Nombre"].str.lower() == nombre_buscar.lower()]
        if resultado.empty:
            print("\nEstudiante no encontrado.")
        else:
            print("\n===== ESTUDIANTE =====")
            print(resultado)

    elif opcion == "9":
        aprobados = df_estudiantes[df_estudiantes["Nota"] >= 70]
        print("\n===== ESTUDIANTES APROBADOS =====")
        print(aprobados)

    elif opcion == "10":
        reprobados = df_estudiantes[df_estudiantes["Nota"] < 70]
        print("\n===== ESTUDIANTES REPROBADOS =====")
        print(reprobados)

    elif opcion == "11":
        promedio = df_estudiantes["Nota"].mean()
        print("\n===== PROMEDIO GENERAL =====")
        print("Promedio:", round(promedio, 2))

    elif opcion == "12":
        promedio_curso = df_estudiantes.groupby("Curso")["Nota"].mean()
        print("\n===== PROMEDIO POR CURSO =====")
        print(promedio_curso.round(2))

    # ------------------------------------------------------
    # OPCIONES RELACIONADAS A LOS ANIMALES
    # ------------------------------------------------------
    elif opcion == "13":
        animal_buscar = input("\n¿Qué animal desea buscar? ")
        resultado = df_animales[df_animales["Animal"].str.lower() == animal_buscar.lower()]
        if resultado.empty:
            print("\nAnimal no encontrado.")
        else:
            print("\n===== ANIMAL ENCONTRADO =====")
            print(resultado.to_string(index=False))

    elif opcion == "14":
        print("\n===== TABLA DE ANIMALES =====")
        print(df_animales.to_string(index=False))

    # ------------------------------------------------------
    # OPCION NOMBRE DEL PROFESOR
    # ------------------------------------------------------
    elif opcion == "15":
        print("\n===== NOMBRE DEL PROFESOR =====")
        print("Berman Alonso Moya Umaña")

    # ------------------------------------------------------
    # SALIR OPCION 16 Y SALIR OPCION ERROR
    # ------------------------------------------------------
    elif opcion == "16":
        print("\nHasta luego! Gracias por usar el programa.")
        break

    else:
        print("\nOpción inválida. Por favor, seleccione una opción del 1 al 16.")